name: Python CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libjpeg-dev \
          libfreetype6-dev \
          liblcms2-dev \
          libopenjp2-7-dev \
          libtiff5-dev \
          libwebp-dev \
          tcl8.6-dev tk8.6-dev python3-tk \
          libcairo2-dev \
          libcups2-dev \
          libffi-dev \
          build-essential \
          python3-dev \
          pkg-config

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-binary=:all: --force-reinstall -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Lint with flake8
      run: |
        flake8 backend tests
